## [作業重點]
使用 Sklearn 中的 Lasso, Ridge 模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義。

機器學習的模型非常多種，但要訓練的資料多半有固定的格式，確保你了解訓練資料的格式為何，這樣在應用新模型時，就能夠最快的上手開始訓練！

## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則化來觀察訓練情形。

In [1]:
import numpy as np
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [4]:
wine = datasets.load_wine()
boston = datasets.load_boston()

In [5]:
wine.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [16]:
x_train, x_test, y_train, y_test = train_test_split(wine.data,wine.target,test_size = 0.3 ,random_state = 1)
regr = linear_model.LinearRegression()
regr.fit(x_train,y_train)
y_pred = regr.predict(x_test)
print("Mean squared error: %f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 0.068565


### Lasso

In [33]:
# 當alpha值=1時，只有一個特徵加權不為零，太稀疏了，所以將alpha改為0.5，MSE有明顯降低
lasso = linear_model.Lasso(alpha=0.5)
lasso.fit(x_train,y_train)
y_pred = lasso.predict(x_test)
print("Mean squared error: %f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 0.241382


In [34]:
lasso.coef_

array([-0.        ,  0.        ,  0.        ,  0.00287995,  0.00050378,
       -0.        , -0.        ,  0.        , -0.        ,  0.07710145,
       -0.        , -0.        , -0.00175513])

### Ridge

In [36]:
ridge = linear_model.Ridge(alpha=10)
ridge.fit(x_train,y_train)
y_pred = ridge.predict(x_test)
print("Mean squared error: %f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 0.068086


In [37]:
ridge.coef_

array([-9.16891400e-02,  3.17937123e-02, -7.02261720e-02,  3.49406919e-02,
       -1.62920286e-04,  1.81938732e-02, -2.81784980e-01, -1.05840213e-02,
        1.54353085e-02,  9.24942420e-02, -9.04048237e-02, -1.84250130e-01,
       -9.25523679e-04])